name = "fanfiction-fyi"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "fanfiction-fyi-db"
database_id = "d4a29888-6e20-4391-8aa0-c131b4c36d88"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "fanfiction-fyi-media"