/**
 * M3 dynamic color theme presets for fanfiction.fyi
 *
 * Each theme maps all --md-sys-color-* tokens to hex values.
 * The `obsidian` theme values are copied directly from theme.css.
 * Other themes are approximated from their seed colors using M3 tonal palette logic.
 */

export interface ThemePreset {
  name: string;
  label: string;
  seed: string;
  colors: Record<string, string>;
}

export const THEMES: Record<string, ThemePreset> = {
  obsidian: {
    name: 'obsidian',
    label: 'Obsidian',
    seed: '#7B8FA8',
    colors: {
      '--md-sys-color-primary': '#B0C4D8',
      '--md-sys-color-on-primary': '#1C2F3F',
      '--md-sys-color-primary-container': '#374A5C',
      '--md-sys-color-on-primary-container': '#D3E4F6',
      '--md-sys-color-secondary': '#A3B8CC',
      '--md-sys-color-on-secondary': '#0D1F30',
      '--md-sys-color-secondary-container': '#2A3E52',
      '--md-sys-color-on-secondary-container': '#C2D6EB',
      '--md-sys-color-tertiary': '#8FA8BF',
      '--md-sys-color-on-tertiary': '#182A3C',
      '--md-sys-color-tertiary-container': '#354A5E',
      '--md-sys-color-on-tertiary-container': '#B8D1E9',
      '--md-sys-color-error': '#FFB4AB',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000A',
      '--md-sys-color-on-error-container': '#FFDAD6',
      '--md-sys-color-surface': '#111418',
      '--md-sys-color-on-surface': '#E1E2E6',
      '--md-sys-color-surface-variant': '#42474E',
      '--md-sys-color-on-surface-variant': '#C2C7CE',
      '--md-sys-color-outline': '#8C9199',
      '--md-sys-color-outline-variant': '#42474E',
      '--md-sys-color-inverse-surface': '#E1E2E6',
      '--md-sys-color-inverse-on-surface': '#2E3035',
      '--md-sys-color-inverse-primary': '#516375',
      '--md-sys-color-surface-dim': '#111418',
      '--md-sys-color-surface-bright': '#373940',
      '--md-sys-color-surface-container-lowest': '#0C0F13',
      '--md-sys-color-surface-container-low': '#191C20',
      '--md-sys-color-surface-container': '#1D2024',
      '--md-sys-color-surface-container-high': '#282A2F',
      '--md-sys-color-surface-container-highest': '#33353A',
    },
  },

  ember: {
    name: 'ember',
    label: 'Ember',
    seed: '#B7845A',
    colors: {
      '--md-sys-color-primary': '#E8BF9A',
      '--md-sys-color-on-primary': '#3E2210',
      '--md-sys-color-primary-container': '#5C3A1E',
      '--md-sys-color-on-primary-container': '#F6DCC5',
      '--md-sys-color-secondary': '#DDB990',
      '--md-sys-color-on-secondary': '#2A1605',
      '--md-sys-color-secondary-container': '#4A3020',
      '--md-sys-color-on-secondary-container': '#F2D5B5',
      '--md-sys-color-tertiary': '#C9A07A',
      '--md-sys-color-on-tertiary': '#2E1A08',
      '--md-sys-color-tertiary-container': '#4F3318',
      '--md-sys-color-on-tertiary-container': '#E4C0A0',
      '--md-sys-color-error': '#FFB4AB',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000A',
      '--md-sys-color-on-error-container': '#FFDAD6',
      '--md-sys-color-surface': '#15120E',
      '--md-sys-color-on-surface': '#E6E0D8',
      '--md-sys-color-surface-variant': '#4E4439',
      '--md-sys-color-on-surface-variant': '#D2C3B5',
      '--md-sys-color-outline': '#9B8E81',
      '--md-sys-color-outline-variant': '#4E4439',
      '--md-sys-color-inverse-surface': '#E6E0D8',
      '--md-sys-color-inverse-on-surface': '#322B24',
      '--md-sys-color-inverse-primary': '#7B5530',
      '--md-sys-color-surface-dim': '#15120E',
      '--md-sys-color-surface-bright': '#3C3730',
      '--md-sys-color-surface-container-lowest': '#0F0D09',
      '--md-sys-color-surface-container-low': '#1D1A15',
      '--md-sys-color-surface-container': '#211E19',
      '--md-sys-color-surface-container-high': '#2C2823',
      '--md-sys-color-surface-container-highest': '#37332D',
    },
  },

  forest: {
    name: 'forest',
    label: 'Forest',
    seed: '#5A8B7A',
    colors: {
      '--md-sys-color-primary': '#A8D4BD',
      '--md-sys-color-on-primary': '#0E2E1F',
      '--md-sys-color-primary-container': '#2D4E3C',
      '--md-sys-color-on-primary-container': '#C4EDDA',
      '--md-sys-color-secondary': '#B8CCBE',
      '--md-sys-color-on-secondary': '#0B2018',
      '--md-sys-color-secondary-container': '#283E30',
      '--md-sys-color-on-secondary-container': '#D0E6D6',
      '--md-sys-color-tertiary': '#9BBFA8',
      '--md-sys-color-on-tertiary': '#0C2615',
      '--md-sys-color-tertiary-container': '#304D38',
      '--md-sys-color-on-tertiary-container': '#B2D4BF',
      '--md-sys-color-error': '#FFB4AB',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000A',
      '--md-sys-color-on-error-container': '#FFDAD6',
      '--md-sys-color-surface': '#0E1510',
      '--md-sys-color-on-surface': '#DDE4DA',
      '--md-sys-color-surface-variant': '#3E4A40',
      '--md-sys-color-on-surface-variant': '#BECAB9',
      '--md-sys-color-outline': '#889486',
      '--md-sys-color-outline-variant': '#3E4A40',
      '--md-sys-color-inverse-surface': '#DDE4DA',
      '--md-sys-color-inverse-on-surface': '#273026',
      '--md-sys-color-inverse-primary': '#447750',
      '--md-sys-color-surface-dim': '#0E1510',
      '--md-sys-color-surface-bright': '#343B34',
      '--md-sys-color-surface-container-lowest': '#090E0A',
      '--md-sys-color-surface-container-low': '#1A201A',
      '--md-sys-color-surface-container': '#1E241F',
      '--md-sys-color-surface-container-high': '#282F29',
      '--md-sys-color-surface-container-highest': '#333A33',
    },
  },

  aurora: {
    name: 'aurora',
    label: 'Aurora',
    seed: '#7A5A8B',
    colors: {
      '--md-sys-color-primary': '#DDBFE8',
      '--md-sys-color-on-primary': '#2D1340',
      '--md-sys-color-primary-container': '#4A2E5C',
      '--md-sys-color-on-primary-container': '#F2DAFA',
      '--md-sys-color-secondary': '#C9B0D6',
      '--md-sys-color-on-secondary': '#16102A',
      '--md-sys-color-secondary-container': '#3E2E4F',
      '--md-sys-color-on-secondary-container': '#E0CCEA',
      '--md-sys-color-tertiary': '#A8C2C8',
      '--md-sys-color-on-tertiary': '#132831',
      '--md-sys-color-tertiary-container': '#374C54',
      '--md-sys-color-on-tertiary-container': '#C0DCE4',
      '--md-sys-color-error': '#FFB4AB',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000A',
      '--md-sys-color-on-error-container': '#FFDAD6',
      '--md-sys-color-surface': '#141218',
      '--md-sys-color-on-surface': '#E6E0E8',
      '--md-sys-color-surface-variant': '#494250',
      '--md-sys-color-on-surface-variant': '#CBC4CE',
      '--md-sys-color-outline': '#958F99',
      '--md-sys-color-outline-variant': '#494250',
      '--md-sys-color-inverse-surface': '#E6E0E8',
      '--md-sys-color-inverse-on-surface': '#322D3A',
      '--md-sys-color-inverse-primary': '#684878',
      '--md-sys-color-surface-dim': '#141218',
      '--md-sys-color-surface-bright': '#3B3740',
      '--md-sys-color-surface-container-lowest': '#0E0C13',
      '--md-sys-color-surface-container-low': '#1C1A21',
      '--md-sys-color-surface-container': '#211E26',
      '--md-sys-color-surface-container-high': '#2B2831',
      '--md-sys-color-surface-container-highest': '#36333C',
    },
  },

  midnight: {
    name: 'midnight',
    label: 'Midnight',
    seed: '#5A6B8B',
    colors: {
      '--md-sys-color-primary': '#ADC2E8',
      '--md-sys-color-on-primary': '#152440',
      '--md-sys-color-primary-container': '#354865',
      '--md-sys-color-on-primary-container': '#CCE0F6',
      '--md-sys-color-secondary': '#A0B0CC',
      '--md-sys-color-on-secondary': '#081A30',
      '--md-sys-color-secondary-container': '#27405A',
      '--md-sys-color-on-secondary-container': '#BDD0EA',
      '--md-sys-color-tertiary': '#96AAC4',
      '--md-sys-color-on-tertiary': '#141E2E',
      '--md-sys-color-tertiary-container': '#35485C',
      '--md-sys-color-on-tertiary-container': '#B4C8E0',
      '--md-sys-color-error': '#FFB4AB',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000A',
      '--md-sys-color-on-error-container': '#FFDAD6',
      '--md-sys-color-surface': '#0C1118',
      '--md-sys-color-on-surface': '#DDE2EA',
      '--md-sys-color-surface-variant': '#3E4550',
      '--md-sys-color-on-surface-variant': '#C0C6D0',
      '--md-sys-color-outline': '#8A909A',
      '--md-sys-color-outline-variant': '#3E4550',
      '--md-sys-color-inverse-surface': '#DDE2EA',
      '--md-sys-color-inverse-on-surface': '#2A3038',
      '--md-sys-color-inverse-primary': '#4870A0',
      '--md-sys-color-surface-dim': '#0C1118',
      '--md-sys-color-surface-bright': '#323840',
      '--md-sys-color-surface-container-lowest': '#070C13',
      '--md-sys-color-surface-container-low': '#171C24',
      '--md-sys-color-surface-container': '#1C2028',
      '--md-sys-color-surface-container-high': '#262B33',
      '--md-sys-color-surface-container-highest': '#31363E',
    },
  },

  paper: {
    name: 'paper',
    label: 'Paper',
    seed: '#8B9DAF',
    colors: {
      '--md-sys-color-primary': '#3B5470',
      '--md-sys-color-on-primary': '#FFFFFF',
      '--md-sys-color-primary-container': '#C6D5E8',
      '--md-sys-color-on-primary-container': '#001E34',
      '--md-sys-color-secondary': '#8B9DAF',
      '--md-sys-color-on-secondary': '#FFFFFF',
      '--md-sys-color-secondary-container': '#E0E8F4',
      '--md-sys-color-on-secondary-container': '#1A2535',
      '--md-sys-color-tertiary': '#6D8BA5',
      '--md-sys-color-on-tertiary': '#FFFFFF',
      '--md-sys-color-tertiary-container': '#CCE0F4',
      '--md-sys-color-on-tertiary-container': '#0A1E30',
      '--md-sys-color-error': '#BA1A1A',
      '--md-sys-color-on-error': '#FFFFFF',
      '--md-sys-color-error-container': '#FFDAD6',
      '--md-sys-color-on-error-container': '#410002',
      '--md-sys-color-surface': '#FAFAFE',
      '--md-sys-color-on-surface': '#1A1C1E',
      '--md-sys-color-surface-variant': '#DFE2EA',
      '--md-sys-color-on-surface-variant': '#434750',
      '--md-sys-color-outline': '#73777F',
      '--md-sys-color-outline-variant': '#C3C6CE',
      '--md-sys-color-inverse-surface': '#2E3035',
      '--md-sys-color-inverse-on-surface': '#F0F0F6',
      '--md-sys-color-inverse-primary': '#AECBE8',
      '--md-sys-color-surface-dim': '#DADAE0',
      '--md-sys-color-surface-bright': '#FAFAFE',
      '--md-sys-color-surface-container-lowest': '#FFFFFF',
      '--md-sys-color-surface-container-low': '#F4F4FA',
      '--md-sys-color-surface-container': '#EEEEF4',
      '--md-sys-color-surface-container-high': '#E8E8EE',
      '--md-sys-color-surface-container-highest': '#E3E3E9',
    },
  },
};

/** Get a list of all theme names */
export const THEME_NAMES = Object.keys(THEMES);

/** Type for theme name */
export type ThemeName = keyof typeof THEMES;