export const prerender = false;

import { getDrizzle } from '@/lib/db';
import { users, pseuds, oauthStates } from '@/lib/schema';
import { createSession, setSessionCookie, getAuth } from '@/lib/auth';
import { jwtVerify, createRemoteJWKSet } from 'jose';
import type { APIRoute } from 'astro';
import { eq, and, ne, sql } from 'drizzle-orm';

// Module-level JWKS — cached and reused across requests to avoid per-request setup cost
const GOOGLE_JWKS = createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'));

/**
 * GET /api/auth/google/callback
 * Google OAuth callback — exchanges code for tokens, handles three flows:
 * 1. New-user signup
 * 2. Existing-user login
 * 3. Account linking (state starts with "link_")
 * D1 eventual consistency: changes may take 500-800ms to be visible in subsequent reads
 */
export const GET: APIRoute = async ({ url, locals, request }) => {
  // TOP-LEVEL SAFETY WRAPPER: catch anything that might escape inner try/catch blocks
  try {
  const d1 = locals.runtime.env.DB as D1Database;
  const db = getDrizzle(d1);
  const env = locals.runtime.env;
  const clientId = env.GOOGLE_CLIENT_ID as string;
  const clientSecret = env.GOOGLE_CLIENT_SECRET as string;
  const founderEmail = (env.FOUNDER_EMAIL as string | undefined)?.trim() || undefined;

  const code = url.searchParams.get('code');
  const error = url.searchParams.get('error');
  const state = url.searchParams.get('state');

  if (error) {
    return Response.redirect(`${url.origin}/login?error=oauth_denied`, 302);
  }

  if (!code) {
    return Response.redirect(`${url.origin}/login?error=oauth_no_code`, 302);
  }

  // --- Link flow: when state starts with "link_", this is an account linking request ---
  if (state && state.startsWith('link_')) {
    // State format: link_{userId} or link_{userId}_{nonce}
    const stateParts = state.slice(5).split('_');
    const linkUserId = parseInt(stateParts[0], 10);
    if (isNaN(linkUserId)) {
      return Response.redirect(`${url.origin}/settings?error=invalid_link_state`, 302);
    }

    // Require auth for linking — verify session user matches the userId in state
    const auth = await getAuth(d1, request);
    if (!auth || auth.user.id !== linkUserId) {
      return Response.redirect(`${url.origin}/settings?error=auth_required`, 302);
    }

    // Validate the state nonce was actually generated by our server
    const oauthState = await db.select().from(oauthStates)
      .where(and(eq(oauthStates.state, state), eq(oauthStates.userId, linkUserId)))
      .get();
    if (!oauthState) {
      return Response.redirect(`${url.origin}/settings?error=invalid_link_state`, 302);
    }
    // Consume the state (one-time use) and clean up expired states
    await db.delete(oauthStates).where(eq(oauthStates.state, state));
    await db.delete(oauthStates).where(sql`created_at < datetime('now', '-10 minutes')`);

    // Exchange code for tokens
    const redirectUri = `${url.origin}/api/auth/google/callback`;
    const tokenRes = await fetch('https://oauth2.googleapis.com/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        code,
        client_id: clientId,
        client_secret: clientSecret,
        redirect_uri: redirectUri,
        grant_type: 'authorization_code',
      }),
    });

    if (!tokenRes.ok) {
      console.error('Google token exchange failed (link flow):', await tokenRes.text());
      return Response.redirect(`${url.origin}/settings?error=oauth_token_failed`, 302);
    }

    const tokens = await tokenRes.json();

    // Verify ID token signature using Google's public JWKS (prevents token forgery)
    let linkPayload: any;
    try {
      const { payload: verified } = await jwtVerify(tokens.id_token as string, GOOGLE_JWKS, {
        issuer: ['accounts.google.com', 'https://accounts.google.com'],
        audience: clientId,
      });
      linkPayload = verified;
    } catch (e) {
      console.error('Google ID token verification failed (link flow):', e);
      return Response.redirect(`${url.origin}/settings?error=oauth_token_failed`, 302);
    }

    const googleEmail = linkPayload.email as string;
    const googleSub = linkPayload.sub as string;
    const googleName = linkPayload.name as string | undefined;
    const googlePicture = linkPayload.picture as string | undefined;

    if (!googleEmail || !googleSub || !linkPayload.email_verified) {
      return Response.redirect(`${url.origin}/settings?error=oauth_no_email`, 302);
    }

    // Check if this Google email is already linked to a DIFFERENT user account
    const existingGoogleUser = await db.select({ id: users.id })
      .from(users)
      .where(and(eq(users.googleId, googleSub), ne(users.id, linkUserId)))
      .get();
    if (existingGoogleUser) {
      return Response.redirect(`${url.origin}/settings?error=google_already_linked`, 302);
    }

    // Also check if another user has the same Google email (less common but possible)
    const existingEmailUser = await db.select({ id: users.id })
      .from(users)
      .where(and(eq(users.email, googleEmail), eq(users.googleId, googleSub), ne(users.id, linkUserId)))
      .get();
    if (existingEmailUser) {
      return Response.redirect(`${url.origin}/settings?error=google_already_linked`, 302);
    }

    // Link Google account to current user
    await db.update(users).set({
      googleId: googleSub,
      avatarUrl: googlePicture ?? null,
      displayName: googleName ?? sql`COALESCE(${users.displayName}, ${googleName ?? null})`,
      updatedAt: sql`(datetime('now'))`,
    }).where(eq(users.id, linkUserId));

    return Response.redirect(`${url.origin}/settings?linked=true`, 302);
  }

  // --- Standard flow: new-user signup or existing-user login ---
  try {
    // Exchange code for tokens
    const redirectUri = `${url.origin}/api/auth/google/callback`;
    const tokenRes = await fetch('https://oauth2.googleapis.com/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        code,
        client_id: clientId,
        client_secret: clientSecret,
        redirect_uri: redirectUri,
        grant_type: 'authorization_code',
      }),
    });

    if (!tokenRes.ok) {
      console.error('Google token exchange failed:', await tokenRes.text());
      return Response.redirect(`${url.origin}/login?error=oauth_token_failed`, 302);
    }

    const tokens = await tokenRes.json();

    // Verify ID token signature using Google's public JWKS (prevents token forgery)
    let payload: any;
    try {
      const { payload: verified } = await jwtVerify(tokens.id_token as string, GOOGLE_JWKS, {
        issuer: ['accounts.google.com', 'https://accounts.google.com'],
        audience: clientId,
      });
      payload = verified;
    } catch (e) {
      console.error('Google ID token verification failed:', e);
      return Response.redirect(`${url.origin}/login?error=oauth_token_failed`, 302);
    }

    const googleEmail = payload.email as string;
    const googleSub = payload.sub as string;
    const googleName = payload.name as string | undefined;
    const googlePicture = payload.picture as string | undefined;

    if (!googleEmail || !payload.email_verified) {
      return Response.redirect(`${url.origin}/login?error=oauth_no_email`, 302);
    }

    // Determine role — founder for specific email (configurable via FOUNDER_EMAIL env var)
    const isFounder = googleEmail === founderEmail;
    const role = isFounder ? 'founder' : 'user';

    // Upsert user — also fetch approved/banned status for login gating
    const existingUser = await db.select({
      id: users.id,
      role: users.role,
      approved: users.approved,
      banned: users.banned,
    }).from(users).where(eq(users.email, googleEmail)).get();

    let userId: number;
    let redirectPath: string;

    if (existingUser) {
      userId = existingUser.id;

      // Banned users cannot log in
      if (existingUser.banned) {
        return Response.redirect(`${url.origin}/login?error=banned`, 302);
      }

      // Update Google fields on existing user (but never downgrade role)
      await db.update(users).set({
        googleId: googleSub,
        avatarUrl: googlePicture ?? null,
        displayName: googleName ?? sql`COALESCE(${users.displayName}, ${googleName ?? null})`,
        updatedAt: sql`(datetime('now'))`,
      }).where(and(eq(users.id, userId), sql`(${users.googleId} IS NULL OR ${users.googleId} != ${googleSub})`));

      // Elevate to founder if applicable (never downgrade)
      if (role === 'founder' && existingUser.role !== 'founder') {
        await db.update(users).set({
          role: 'founder',
          updatedAt: sql`(datetime('now'))`,
        }).where(eq(users.id, userId));
      }

      // Unapproved users go to pending-approval page
      redirectPath = existingUser.approved ? '/' : '/pending-approval';
    } else {
      // Create new OAuth user — new users require approval (approved = 0)
      // Exception: founder is auto-approved
      const approved = isFounder ? 1 : 0;
      const result = await db.insert(users).values({
        email: googleEmail,
        role,
        googleId: googleSub,
        avatarUrl: googlePicture ?? null,
        displayName: googleName ?? null,
        approved,
        createdAt: sql`(datetime('now'))`,
        updatedAt: sql`(datetime('now'))`,
      }).returning({ id: users.id });
      userId = result[0].id;

      // Create default pseud from Google name or email local part
      const pseudName = googleName || googleEmail.split('@')[0];
      await db.insert(pseuds).values({
        userId,
        name: pseudName,
        createdAt: sql`(datetime('now'))`,
      });

      // New users go to pending-approval unless they're the founder
      redirectPath = isFounder ? '/' : '/pending-approval';
    }

    // Create session
    const token = await createSession(d1, userId);

    // Redirect to appropriate page with session cookie
    return new Response(null, {
      status: 302,
      headers: {
        Location: redirectPath,
        'Set-Cookie': setSessionCookie(token),
      },
    });
  } catch (err) {
    console.error('Google OAuth callback error (standard flow):', err);
    const errDetail = err instanceof Error ? `${err.message}|${err.stack?.slice(0, 200)}` : String(err);
    return Response.redirect(`${url.origin}/login?error=oauth_callback_failed&detail=${encodeURIComponent(errDetail.slice(0, 300))}`, 302);
  }

  } catch (topLevelErr) {
    // SAFETY NET: catch any unhandled errors at the module/handler level
    console.error('Google OAuth callback TOP-LEVEL error:', topLevelErr);
    const detail = topLevelErr instanceof Error ? `${topLevelErr.message}__STACK__${topLevelErr.stack?.slice(0, 500)}` : String(topLevelErr);
    return new Response(JSON.stringify({ error: 'internal', detail }), {
      status: 500,
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
    });
  }
};